version: '2'

services:

  packagist:
    restart: always
    # image: dockette/packagist:packagist
    build: ./packagist

    ports:
      # Production mode
      - 8000:8000
      - 80:8000
      #- 443:8000
      # Development mode
      - 9000:9000
      # Supervisor
      #- 9001:9001

      # You should create your own SSH keys
      # ===================================
#    volumes:
#       - ./config/ssh/config:/var/www/.ssh/config
#       - ./config/ssh/id_ed25519:/var/www/.ssh/id_ed25519
#       - ./config/ssh/id_ed25519.pub:/var/www/.ssh/id_ed25519.pub
#       - ./config/ssh/known_hosts:/var/www/.ssh/known_hosts

    environment:
      - APP_HOSTNAME='packagist.local:8000'
      - APP_SCHEME=http
      - ALGOLIA_HOST=packagist.local:8000/search2
      - PACKAGIST_DATABASE_DSN=mysqli://packagist:packagist@mysql:3306/packagist?serverVersion=10.2.12
   # extra_hosts:
     # - "packagist.local:10.77.77.199"
    depends_on:
      - mysql
      - redis
      - solr

  mysql:
    restart: always
    image: mariadb:latest

    volumes:
      - ./data/mysql:/var/lib/mysql
#    ports:
#      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=packagist
      - MYSQL_USER=packagist
      - MYSQL_PASSWORD=packagist

  redis:
    restart: always
    image: redis:3.2

    volumes:
      - ./data/redis:/data

  solr:
    image: dockette/packagist:solr
    ports:
      - 8983:8983
    volumes:
      - ./data/solr:/opt/solr/server/solr/mycores
